### ISSUE TITLE
error analyzing a boot.img

### ISSUE THREAD

**Issue by carlitros900** [marin-m/vmlinux-to-elf#17]
Error analyzing the attached boot.img

[boot.gz](https://github.com/marin-m/vmlinux-to-elf/files/5082848/boot.gz)

`[+] Kernel successfully decompressed in-memory (the offsets that follow will be given relative to the decompressed binary)`
`[+] Version string: Linux version 4.9.117-g039ca999a0ec-dirty (build@i3-ri-14-use1a-b-87) (gcc version 6.3.1 20170404 (Linaro GCC 6.3-2017.05) ) #1 SMP PREEMPT Mon Aug 3 01:09:46 UTC 2020`
`[+] Guessed architecture: armle successfully in 8.58 seconds`
`[+] Found kallsyms_token_table at file offset 0x00d660e0`
`[+] Found kallsyms_token_index at file offset 0x00d66430`
`Traceback (most recent call last):`
 ` File "vmlinux-to-elf/vmlinux_to_elf/main.py", line 61, in <module>`
`    ElfSymbolizer(`
`  File "/media/android/ab5d60f6-9904-42cf-9ca2-c9af2dc4f3da/AC101BOX/androiddumps/dumpyara/vmlinux-to-elf/vmlinux_to_elf/elf_symbolizer.py", line 44, in __init__`
`    kallsyms_finder = KallsymsFinder(file_contents, bit_size)`
`  File "/media/android/ab5d60f6-9904-42cf-9ca2-c9af2dc4f3da/AC101BOX/androiddumps/dumpyara/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 208, in __init__`
`    self.find_kallsyms_markers()`
`  File "/media/android/ab5d60f6-9904-42cf-9ca2-c9af2dc4f3da/AC101BOX/androiddumps/dumpyara/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 697, in find_kallsyms_markers`
`    raise ValueError('Could not guess the architecture register ' +`
`ValueError: Could not guess the architecture register size for kernel
`

Thanks

**Comment by marin-m** [comment]
Fixed in commit 8399802, thanks!
