### ISSUE TITLE
get kallsysms as txt

### ISSUE THREAD

**Issue by DrRamm** [marin-m/vmlinux-to-elf#2]
Is it possible provide any way to get kallsyms in format like `cat /proc/kallsyms `? 
I mean this 
```
c0093440 t devkmsg_llseek
c009351c t devkmsg_read
c00939b0 t log_make_free_space
c0093ad8 t log_store
```

**Comment by marin-m** [comment]
Hello,

For this, you have an utility that does almost this, called `kallsyms_finder`, that is bundled with `vmlinux-to-elf`.

It outputs the information rather like this:

```
'tdevkmsg_llseek'                                                 0xffffffff810f0200
```

Maybe that you would like the output of `kallsyms-finder` to be identical for compatibility purposes however?

**Comment by marin-m** [comment]
Hello,

For your information, the output of the `kallsyms-finder` command has been aligned on the `/proc/kallsyms` output format.

Regards,
