### ISSUE TITLE
ValueError: 2 candidates for kallsyms_token_table in kernel image

### ISSUE THREAD

**Issue by csersoft** [marin-m/vmlinux-to-elf#21]
Hello, I encountered a problem when using this tool, the output is as follows:

> $ vmlinux-to-elf kernel.uimage kernel.elf
[+] Kernel successfully decompressed in-memory (the offsets that follow will be given relative to the decompressed binary)
[+] Version string: Linux version 2.6.32.61-EMBSYS-CGEL-4.03.20.P1.F0 (root@A000001) (gcc version 4.5.2 2015-05-12 ZTE Embsys-TSP Vn (GCC) ) #102 Thu Jan 25 05:19:23 CST 2018
[+] Guessed architecture: armle successfully in 3.70 seconds
Traceback (most recent call last):
  File "/usr/local/bin/vmlinux-to-elf", line 67, in <module>
    args.base_address, args.file_offset
  File "/usr/local/bin/vmlinux_to_elf/elf_symbolizer.py", line 44, in __init__
    kallsyms_finder = KallsymsFinder(file_contents, bit_size)
  File "/usr/local/bin/vmlinux_to_elf/kallsyms_finder.py", line 193, in __init__
    self.find_kallsyms_token_table()
  File "/usr/local/bin/vmlinux_to_elf/kallsyms_finder.py", line 411, in find_kallsyms_token_table
    raise ValueError('%d candidates for kallsyms_token_table in kernel image' % len(candidates_offsets))
ValueError: 2 candidates for kallsyms_token_table in kernel image

Kernel file not working properly: [kernel.zip](https://github.com/marin-m/vmlinux-to-elf/files/5600649/kernel.zip)

**Comment by marin-m** [comment]
Hello,

I have pushed a fix in commit 0c67469. This seems to work now.

Regards,

**Comment by csersoft** [comment]
Thanks!
