### ISSUE TITLE
ValueError: 3 candidates for kallsyms_token_table in kernel image

### ISSUE THREAD

**Issue by csersoft** [marin-m/vmlinux-to-elf#22]
Hello, I found that a new kernel image will have the same error #21 :

> $ vmlinux-to-elf kernel.bin kernel.elf
> [+] Kernel successfully decompressed in-memory (the offsets that follow will be given relative to the decompressed binary)
> [+] Version string: Linux version 2.6.32.61-EMBSYS-CGEL-4.03.20.P1.F0 (wuxianglong@zxric-nb) (gcc version 4.1.2 2011-06-24 ZTE Embsys-TSP V2.08.20_P2) #108 Fri Apr 26 20:57:18 CST 2019
> [+] Guessed architecture: armle successfully in 3.96 seconds
> Traceback (most recent call last):
>   File "/usr/local/bin/vmlinux-to-elf", line 67, in <module>
>     args.base_address, args.file_offset
>   File "/usr/local/bin/vmlinux_to_elf/elf_symbolizer.py", line 44, in __init__
>     kallsyms_finder = KallsymsFinder(file_contents, bit_size)
>   File "/usr/local/bin/vmlinux_to_elf/kallsyms_finder.py", line 193, in __init__
>     self.find_kallsyms_token_table()
>   File "/usr/local/bin/vmlinux_to_elf/kallsyms_finder.py", line 417, in find_kallsyms_token_table
>     raise ValueError('%d candidates for kallsyms_token_table in kernel image' % len(candidates_offsets))
> ValueError: 3 candidates for kallsyms_token_table in kernel image

Kernel file: [kernel2.zip](https://github.com/marin-m/vmlinux-to-elf/files/5610319/kernel2.zip)

Regards.

**Comment by marin-m** [comment]
Fixed in commit d5b0758, thanks
