### ISSUE TITLE
Android bootimg support

### ISSUE THREAD

**Issue by zachriggle** [marin-m/vmlinux-to-elf#26]
It would be nice if the Android boot image (`ANDROID!` magic) format was supported by this tool.

Pwntools has a utility for extracting these, so you might be able to borrow some of that code:
https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/adb/bootimg.py

**Comment by marin-m** [comment]
Hello,

Good idea, I added something in commit 4adff5b.

Thank you!

**Comment by tiann** [comment]
I have tested many Android boot images and it works great, i think the issue can be closed.
