### ISSUE TITLE
Performance: ElfStrtab is slow

### ISSUE THREAD

**Issue by Myldero** [marin-m/vmlinux-to-elf#39]
`add_string_and_return_offset` runs in O(n) time, since it needs to scan the entirety of `raw_string_table` every time. This makes adding all of the symbols run in O(n²) time which on my machine takes around 30 seconds.

`return_string_from_offset` runs in O(n) time. It takes a slice of `raw_string_table` which will copy the entirety of `raw_string_table` from offset to a new bytes object.

**Comment by marin-m** [comment]
Pull request merged, thanks
