### ISSUE TITLE
Could not guess the architecture register size for kernel

### ISSUE THREAD

**Issue by hiro4bbh** [marin-m/vmlinux-to-elf#49]
I encountered the following error with commit <https://github.com/marin-m/vmlinux-to-elf/commit/f86fff01fc5ed047da0eeb6b0f6824fad44048ee>, as trying to extract kallsyms from vmlinux of <https://2022.ctf.link/internal/challenge/0a8dd8e2-de2f-4eff-97d7-643c6f28dc22>.

```
# kallsyms-finder ./vmlinux 
[+] Version string: Linux version 6.2.2 (sisu@sisu-ThinkPad-E14-Gen-2) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) # SMP PREEMPT_DYNAMIC 
[+] Guessed architecture: x86_64 successfully in 3.74 seconds
[+] Found kallsyms_token_table at file offset 0x018e75b0
[+] Found kallsyms_token_index at file offset 0x018e7950
Traceback (most recent call last):
  File "/usr/local/bin/kallsyms-finder", line 1145, in <module>
    kallsyms = KallsymsFinder(obtain_raw_kernel_from_file(kernel_bin.read()), args.bit_size)
  File "/usr/local/bin/kallsyms-finder", line 208, in __init__
    self.find_kallsyms_markers()
  File "/usr/local/bin/kallsyms-finder", line 720, in find_kallsyms_markers
    raise ValueError('Could not guess the architecture register ' +
ValueError: Could not guess the architecture register size for kernel
```

(I extract vmlinux from bzImage with <https://raw.githubusercontent.com/torvalds/linux/v5.15/scripts/extract-vmlinux>. Make sure that lzop and zstd are also installed.)

I cannot figure out how to solve this.
Simply setting `max_number_of_space_between_two_nulls` is one of `2`, `4` or `8`, another error occurs ...: `Could not find kallsyms_markers`

**Comment by Myldero** [comment]
Looks like breaking changes in kernel v6.1. From testing, the commit in question seems to be this one https://github.com/torvalds/linux/commit/19bd8981dc2ee35fdc81ab1b0104b607c917d470
