### ISSUE TITLE
I got this err

### ISSUE THREAD

**Issue by jelasin** [marin-m/vmlinux-to-elf#58]
![图片](https://github.com/marin-m/vmlinux-to-elf/assets/97788570/d45ed37e-887c-40d1-ac24-466b18174208)

**Comment by marin-m** [comment]
Hello,

The error message seems pretty explicit, the connection to Github from `pip3` did not succeed.

Is your connection working correctly? Are you in a location with restricted Internet access like China/are you using a VPN/surfing over a radio cell connection? Did you retry performing the install step?

Regards,

**Comment by jelasin** [comment]
thanks, I had retry it, it's worked.
