### ISSUE TITLE
backward lookup hasn't enough steps

### ISSUE THREAD

**Issue by screwer** [marin-m/vmlinux-to-elf#9]
Kernel from Nokia7 failed to process with exception 'This structure is not a kallsyms_token_table'
Simple increase '20' to '50' solves the problem. But it is dirty hack (i haven't enough time to solve cause.

Example kernel binary: http://omegahg.com/temp/kernel.7z

**Comment by marin-m** [comment]
Thanks. Indeed Nokia seems to use some fancy long method symbol prefixes. Tested on my dataset and fixed in commit e822b28
